name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t javascript-calculator .
      
    - name: Run tests
      run: docker run --rm javascript-calculator node node_modules/jest/bin/jest.js --config ./config/jest.config.js
